### ISSUE TITLE
Install flickity post install

### ISSUE THREAD

**Issue by briangonzalez** [travelbank/ember-flickity#2]
à la ember-cli-sentry

https://github.com/damiencaselli/ember-cli-sentry/blob/ed0360a2aff6399b2fa791b211777f2a1c1740bc/blueprints/ember-cli-sentry/index.js#L8-L12

**Comment by dylanfoster** [comment]
We're already doing [this](https://github.com/travelbank/ember-flickity/blob/master/blueprints/ember-flickity/index.js), the only difference is the specific target, unless I missed something?

**Comment by briangonzalez** [comment]
Whoops, ok! My bad, I missed it.
